[project]
name = "vshieldapi"
version = "0.0.1"
authors = [
  {name="Tayfun Bocek", email="tayfunbocek@live.ca"},
]
description = "Python library for the vShield API."
requires-python = ">=3.10"
dependencies = ["httpx", "httpx[http2]"]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.black]
target-version = ["py311"]
include = '''
(
  ^.*\.py
)
'''

[tool.ruff]
extend-select = [
  "D", "I"
]
extend-ignore = ["D107"]
fixable = ["I001"]
line-length = 88

[tool.ruff.per-file-ignores]
"__init__.py" = ["F401"]

[tool.ruff.pydocstyle]
convention = "google"